### ISSUE TITLE
Giving error when loaded

### ISSUE THREAD

**Issue by joppari** [Alemiz112/StarGate-Atlantis#14]
When loading the plugin it gives errer message 

"Fatal error: Uncaught Error: Call to undefined method alemiz\sga\client\StarGateConnection::registerClassLoader() in /home/container/plugins/StarGate-Atlantis-pmmp-4/src/alemiz/sga/client/StarGateConnection.php:86
Stack trace:
#0 phar:///home/container/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(93): alemiz\sga\client\StarGateConnection->onRun()
#1 [internal function]: pocketmine\thread\Thread->run()
#2 {main}
  thrown in /home/container/plugins/StarGate-Atlantis-pmmp-4/src/alemiz/sga/client/StarGateConnection.php on line 86"
  
  
  
    Reproduction : 
    
    1. Create PMMP4 server
    2. Install Stargate - Atlantis pmmp4 branch
    3. Start it

**Comment by Alemiz112** [comment]
Hi, it seems to be caused by different PM 4 thread api.

Replacing `registerClassLoader()` with [`registerClassLoaders()`](https://github.com/pmmp/PocketMine-MP/blob/5fbc7681b04fe702fcbd43940b9d325e5c216707/src/thread/CommonThreadPartsTrait.php#L75) should probably work. I will take a look on it bit later.

**Comment by joppari** [comment]
Ok thank you

**Comment by joppari** [comment]
fixed in #16
